<?php
namespace WorkforceOne\Api\Auth;

if (!defined('ABSPATH')) exit;

/**
 * Checks the body of POST /auth/login. Pure.
 *
 * { "username": "...", "password": "...",
 *   "device": { "installation_id": "...", "platform": "android|ios", "model": "...", "app_version": "1.2.0" } }
 *
 * The installation id identifies one installation of the app (generated by the app, kept in its
 * storage); it is not proof of anything. No other device data is collected.
 */
final class LoginInput
{
    public const PLATFORMS = ['android', 'ios'];

    /**
     * @param mixed $body the decoded JSON body
     * @return array{0:array{username:string,password:string,device:array{installation_id:string,platform:string,model:string,app_version:string}}|null,1:array<string,string>}
     *         [input, errors by field]
     */
    public static function parse($body): array
    {
        $errors = [];
        $body = is_array($body) ? $body : [];
        $username = $body['username'] ?? null;
        $password = $body['password'] ?? null;
        if (!is_string($username) || trim($username) === '' || strlen($username) > 200) $errors['username'] = 'required';
        if (!is_string($password) || $password === '' || strlen($password) > 4096) $errors['password'] = 'required';
        $d = is_array($body['device'] ?? null) ? $body['device'] : [];
        $device = [
            'installation_id' => is_string($d['installation_id'] ?? null) ? trim($d['installation_id']) : '',
            'platform' => is_string($d['platform'] ?? null) ? strtolower(trim($d['platform'])) : '',
            'model' => is_string($d['model'] ?? null) ? trim($d['model']) : '',
            'app_version' => is_string($d['app_version'] ?? null) ? trim($d['app_version']) : '',
        ];
        if (!preg_match('/^[A-Za-z0-9._:-]{8,100}$/D', $device['installation_id'])) $errors['device.installation_id'] = 'invalid';
        if (!in_array($device['platform'], self::PLATFORMS, true)) $errors['device.platform'] = 'invalid';
        if ($device['model'] === '' || strlen($device['model']) > 100 || preg_match('/[\x00-\x1f\x7f]/', $device['model'])) $errors['device.model'] = 'invalid';
        if (!preg_match('/^\d{1,4}(\.\d{1,4}){0,3}([+-][A-Za-z0-9.]{1,20})?$/D', $device['app_version'])) $errors['device.app_version'] = 'invalid';
        if ($errors) return [null, $errors];
        return [['username' => (string) $username, 'password' => (string) $password, 'device' => $device], []];
    }
}
